package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,schema="public"
)
public class Categoria  implements java.io.Serializable {


     private String idCategoria;
     private String nombre;
     private String descripcion;
     private Set<ItemMenu> itemMenus = new HashSet<ItemMenu>(0);

    public Categoria() {
    }

	
    public Categoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(String idCategoria, String nombre, String descripcion, Set<ItemMenu> itemMenus) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.itemMenus = itemMenus;
    }
   
    @Id    
    @Column(name="id_categoria", nullable=false, length=10)
    public String getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="nombre", length=15)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set<ItemMenu> getItemMenus() {
        return this.itemMenus;
    }
    
    public void setItemMenus(Set<ItemMenu> itemMenus) {
        this.itemMenus = itemMenus;
    }




}


