package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacturaItemsId generated by hbm2java
 */
@Embeddable
public class FacturaItemsId  implements java.io.Serializable {


     private String idItem;
     private String idFactura;

    public FacturaItemsId() {
    }

    public FacturaItemsId(String idItem, String idFactura) {
       this.idItem = idItem;
       this.idFactura = idFactura;
    }
   


    @Column(name="id_item", length=10)
    public String getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(String idItem) {
        this.idItem = idItem;
    }


    @Column(name="id_factura", length=10)
    public String getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(String idFactura) {
        this.idFactura = idFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaItemsId) ) return false;
		 FacturaItemsId castOther = ( FacturaItemsId ) other; 
         
		 return ( (this.getIdItem()==castOther.getIdItem()) || ( this.getIdItem()!=null && castOther.getIdItem()!=null && this.getIdItem().equals(castOther.getIdItem()) ) )
 && ( (this.getIdFactura()==castOther.getIdFactura()) || ( this.getIdFactura()!=null && castOther.getIdFactura()!=null && this.getIdFactura().equals(castOther.getIdFactura()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdItem() == null ? 0 : this.getIdItem().hashCode() );
         result = 37 * result + ( getIdFactura() == null ? 0 : this.getIdFactura().hashCode() );
         return result;
   }   


}


