package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacturaFormaPagoId generated by hbm2java
 */
@Embeddable
public class FacturaFormaPagoId  implements java.io.Serializable {


     private String idPago;
     private String idFactura;

    public FacturaFormaPagoId() {
    }

    public FacturaFormaPagoId(String idPago, String idFactura) {
       this.idPago = idPago;
       this.idFactura = idFactura;
    }
   


    @Column(name="id_pago", length=10)
    public String getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(String idPago) {
        this.idPago = idPago;
    }


    @Column(name="id_factura", length=10)
    public String getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(String idFactura) {
        this.idFactura = idFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaFormaPagoId) ) return false;
		 FacturaFormaPagoId castOther = ( FacturaFormaPagoId ) other; 
         
		 return ( (this.getIdPago()==castOther.getIdPago()) || ( this.getIdPago()!=null && castOther.getIdPago()!=null && this.getIdPago().equals(castOther.getIdPago()) ) )
 && ( (this.getIdFactura()==castOther.getIdFactura()) || ( this.getIdFactura()!=null && castOther.getIdFactura()!=null && this.getIdFactura().equals(castOther.getIdFactura()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPago() == null ? 0 : this.getIdPago().hashCode() );
         result = 37 * result + ( getIdFactura() == null ? 0 : this.getIdFactura().hashCode() );
         return result;
   }   


}


