package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FacturaFormaPago generated by hbm2java
 */
@Entity
@Table(name="factura_forma_pago"
    ,schema="public"
)
public class FacturaFormaPago  implements java.io.Serializable {


     private FacturaFormaPagoId id;
     private Factura factura;
     private FormaPago formaPago;

    public FacturaFormaPago() {
    }

	
    public FacturaFormaPago(FacturaFormaPagoId id) {
        this.id = id;
    }
    public FacturaFormaPago(FacturaFormaPagoId id, Factura factura, FormaPago formaPago) {
       this.id = id;
       this.factura = factura;
       this.formaPago = formaPago;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPago", column=@Column(name="id_pago", length=10) ), 
        @AttributeOverride(name="idFactura", column=@Column(name="id_factura", length=10) ) } )
    public FacturaFormaPagoId getId() {
        return this.id;
    }
    
    public void setId(FacturaFormaPagoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_factura", insertable=false, updatable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pago", insertable=false, updatable=false)
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }




}


