package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FacturaItems generated by hbm2java
 */
@Entity
@Table(name="factura_items"
    ,schema="public"
)
public class FacturaItems  implements java.io.Serializable {


     private FacturaItemsId id;
     private Factura factura;
     private ItemMenu itemMenu;

    public FacturaItems() {
    }

	
    public FacturaItems(FacturaItemsId id) {
        this.id = id;
    }
    public FacturaItems(FacturaItemsId id, Factura factura, ItemMenu itemMenu) {
       this.id = id;
       this.factura = factura;
       this.itemMenu = itemMenu;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idItem", column=@Column(name="id_item", length=10) ), 
        @AttributeOverride(name="idFactura", column=@Column(name="id_factura", length=10) ) } )
    public FacturaItemsId getId() {
        return this.id;
    }
    
    public void setId(FacturaItemsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_factura", insertable=false, updatable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_item", insertable=false, updatable=false)
    public ItemMenu getItemMenu() {
        return this.itemMenu;
    }
    
    public void setItemMenu(ItemMenu itemMenu) {
        this.itemMenu = itemMenu;
    }




}


