package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name="forma_pago"
    ,schema="public"
)
public class FormaPago  implements java.io.Serializable {


     private String idPago;
     private String nombre;
     private String descripcion;
     private Set<FacturaFormaPago> facturaFormaPagos = new HashSet<FacturaFormaPago>(0);

    public FormaPago() {
    }

	
    public FormaPago(String idPago) {
        this.idPago = idPago;
    }
    public FormaPago(String idPago, String nombre, String descripcion, Set<FacturaFormaPago> facturaFormaPagos) {
       this.idPago = idPago;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.facturaFormaPagos = facturaFormaPagos;
    }
   
     @Id 

    
    @Column(name="id_pago", nullable=false, length=10)
    public String getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(String idPago) {
        this.idPago = idPago;
    }

    
    @Column(name="nombre", length=10)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPago")
    public Set<FacturaFormaPago> getFacturaFormaPagos() {
        return this.facturaFormaPagos;
    }
    
    public void setFacturaFormaPagos(Set<FacturaFormaPago> facturaFormaPagos) {
        this.facturaFormaPagos = facturaFormaPagos;
    }




}


