package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemMenu generated by hbm2java
 */
@Entity
@Table(name="item_menu"
    ,schema="public"
)
public class ItemMenu  implements java.io.Serializable {


     private String idItem;
     private Categoria categoria;
     private String fotografia;
     private Integer precioActual;
     private String descripcion;
     private Integer cantidadDisponible;
     private Set<FacturaItems> facturaItemses = new HashSet<FacturaItems>(0);
     private Set<PedidoItem> pedidoItems = new HashSet<PedidoItem>(0);

    public ItemMenu() {
    }

	
    public ItemMenu(String idItem) {
        this.idItem = idItem;
    }
    public ItemMenu(String idItem, Categoria categoria, String fotografia, Integer precioActual, String descripcion, Integer cantidadDisponible, Set<FacturaItems> facturaItemses, Set<PedidoItem> pedidoItems) {
       this.idItem = idItem;
       this.categoria = categoria;
       this.fotografia = fotografia;
       this.precioActual = precioActual;
       this.descripcion = descripcion;
       this.cantidadDisponible = cantidadDisponible;
       this.facturaItemses = facturaItemses;
       this.pedidoItems = pedidoItems;
    }
   
     @Id 

    
    @Column(name="id_item", nullable=false, length=10)
    public String getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(String idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria")
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="fotografia", length=50)
    public String getFotografia() {
        return this.fotografia;
    }
    
    public void setFotografia(String fotografia) {
        this.fotografia = fotografia;
    }

    
    @Column(name="precio_actual")
    public Integer getPrecioActual() {
        return this.precioActual;
    }
    
    public void setPrecioActual(Integer precioActual) {
        this.precioActual = precioActual;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="cantidad_disponible")
    public Integer getCantidadDisponible() {
        return this.cantidadDisponible;
    }
    
    public void setCantidadDisponible(Integer cantidadDisponible) {
        this.cantidadDisponible = cantidadDisponible;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemMenu")
    public Set<FacturaItems> getFacturaItemses() {
        return this.facturaItemses;
    }
    
    public void setFacturaItemses(Set<FacturaItems> facturaItemses) {
        this.facturaItemses = facturaItemses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemMenu")
    public Set<PedidoItem> getPedidoItems() {
        return this.pedidoItems;
    }
    
    public void setPedidoItems(Set<PedidoItem> pedidoItems) {
        this.pedidoItems = pedidoItems;
    }




}


