package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PedidoItemId generated by hbm2java
 */
@Embeddable
public class PedidoItemId  implements java.io.Serializable {


     private String idPedido;
     private String idItem;

    public PedidoItemId() {
    }

    public PedidoItemId(String idPedido, String idItem) {
       this.idPedido = idPedido;
       this.idItem = idItem;
    }
   


    @Column(name="id_pedido", length=10)
    public String getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(String idPedido) {
        this.idPedido = idPedido;
    }


    @Column(name="id_item", length=10)
    public String getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(String idItem) {
        this.idItem = idItem;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidoItemId) ) return false;
		 PedidoItemId castOther = ( PedidoItemId ) other; 
         
		 return ( (this.getIdPedido()==castOther.getIdPedido()) || ( this.getIdPedido()!=null && castOther.getIdPedido()!=null && this.getIdPedido().equals(castOther.getIdPedido()) ) )
 && ( (this.getIdItem()==castOther.getIdItem()) || ( this.getIdItem()!=null && castOther.getIdItem()!=null && this.getIdItem().equals(castOther.getIdItem()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPedido() == null ? 0 : this.getIdPedido().hashCode() );
         result = 37 * result + ( getIdItem() == null ? 0 : this.getIdItem().hashCode() );
         return result;
   }   


}


