package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PedidoItem generated by hbm2java
 */
@Entity
@Table(name="pedido_item"
    ,schema="public"
)
public class PedidoItem  implements java.io.Serializable {


     private PedidoItemId id;
     private ItemMenu itemMenu;
     private Pedido pedido;

    public PedidoItem() {
    }

	
    public PedidoItem(PedidoItemId id) {
        this.id = id;
    }
    public PedidoItem(PedidoItemId id, ItemMenu itemMenu, Pedido pedido) {
       this.id = id;
       this.itemMenu = itemMenu;
       this.pedido = pedido;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPedido", column=@Column(name="id_pedido", length=10) ), 
        @AttributeOverride(name="idItem", column=@Column(name="id_item", length=10) ) } )
    public PedidoItemId getId() {
        return this.id;
    }
    
    public void setId(PedidoItemId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_item", insertable=false, updatable=false)
    public ItemMenu getItemMenu() {
        return this.itemMenu;
    }
    
    public void setItemMenu(ItemMenu itemMenu) {
        this.itemMenu = itemMenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedido", insertable=false, updatable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }




}


