package entity;
// Generated 26/04/2017 03:04:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,schema="public"
)
public class Personal  implements java.io.Serializable {


     private String idPersonal;
     private String nombre;
     private String apellido;
     private String tipoIdentificacion;
     private String cargo;
     private String horarioTurno;
     private String foto;
     private String direccion;
     private String telefonoFijo;
     private String telefonoCelular;
     private String correo;
     private String contrasena;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Personal() {
    }

	
    public Personal(String idPersonal) {
        this.idPersonal = idPersonal;
    }
    public Personal(String idPersonal, String nombre, String apellido, String tipoIdentificacion, String cargo, String horarioTurno, String foto, String direccion, String telefonoFijo, String telefonoCelular, String correo, String contrasena, Set<Factura> facturas, Set<Pedido> pedidos) {
       this.idPersonal = idPersonal;
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipoIdentificacion = tipoIdentificacion;
       this.cargo = cargo;
       this.horarioTurno = horarioTurno;
       this.foto = foto;
       this.direccion = direccion;
       this.telefonoFijo = telefonoFijo;
       this.telefonoCelular = telefonoCelular;
       this.correo = correo;
       this.contrasena = contrasena;
       this.facturas = facturas;
       this.pedidos = pedidos;
    }
   
     @Id 

    
    @Column(name="id_personal", nullable=false, length=10)
    public String getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(String idPersonal) {
        this.idPersonal = idPersonal;
    }

    
    @Column(name="nombre", length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=20)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="tipo_identificacion", length=20)
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }

    
    @Column(name="cargo", length=20)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="horario_turno", length=20)
    public String getHorarioTurno() {
        return this.horarioTurno;
    }
    
    public void setHorarioTurno(String horarioTurno) {
        this.horarioTurno = horarioTurno;
    }

    
    @Column(name="foto", length=50)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    
    @Column(name="direccion", length=30)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono_fijo", length=10)
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }

    
    @Column(name="telefono_celular", length=10)
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }

    
    @Column(name="correo", length=30)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="contrasena", length=30)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


